notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - curl --silent -L "https://s3-us-west-1.amazonaws.com/kite-data/tensorflow/libtensorflow-cpu-`go env GOOS`-x86_64-1.9.0.tar.gz" | tar -C $HOME -xz
  - export LD_LIBRARY_PATH="$HOME/lib:$LD_LIBRARY_PATH"
  - curl --silent --compressed --output "$HOME/kited-test" "https://s3-us-west-1.amazonaws.com/kited-test/darwin/kited-test"
  - chmod u+x "$HOME/kited-test"
  - $HOME/kited-test > ~/kited-test.log 2>&1 & sleep 10

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

sudo: false

language: node_js

node_js:
- "node"

os:
- osx

env:
  global:
  - LIVE_ENVIRONMENT=1
  - APM_TEST_PACKAGES=""
  - CC=gcc-4.8 CXX=g++-4.8

  matrix:
  - ATOM_CHANNEL=stable
  - ATOM_CHANNEL=beta
